# Generated by Django 3.1 on 2020-09-12 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicInformation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApptSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeOfAppt', models.DateTimeField(auto_now=True)),
                ('duration', models.TimeField(verbose_name='min')),
                ('attended', models.BooleanField(default=False)),
                ('user_apptSchedule', models.CharField(max_length=64)),
                ('doctor_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='clinicInformation.doctorclinic', verbose_name='doctorName')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='username')),
            ],
        ),
    ]
