# Generated by Django 3.1 on 2020-09-12 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorClinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=256)),
                ('specialty', models.CharField(max_length=100)),
                ('clinic_name', models.CharField(max_length=256)),
                ('clinic_street', models.CharField(max_length=1000)),
                ('clinic_city', models.CharField(max_length=256)),
                ('clinic_state', models.CharField(max_length=200)),
                ('clinic_country', models.CharField(max_length=200)),
                ('clinic_zipcode', models.IntegerField(max_length=6)),
                ('doctor_id', models.CharField(max_length=64)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='username')),
            ],
        ),
    ]
